name: Hello World
on: 
    push:
        branches: [main]
        paths-ignore:
            - ".github/workflows/*"
    pull_request:
        branches: [main]
        
    repository_dispatch:
        types: ["on-demand-test"]

jobs:
  echo-vars:
    runs-on: ubuntu-latest
    steps:
     - name: Echo Github Variable
       run: |
         echo "This job trigger by ${{ github.event_name }}";
         echo "This repository is ${{ github.repository }}";
         echo "This branch is ${{ github.ref_name }}"
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello from GitHub Actions!"
        
      - name: Retrieve client payload
        run: echo "Client send status = ${{ github.event.client_payload.status }}"
        
  second-job:
    runs-on: windows-latest
    needs: hello-job
    steps:
     - run: echo "This job is running on ${{ runner.os }}"
