on:
  workflow_dispatch:

jobs:
  buildId:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref_name }}
      - name: List files in workspace
        run: ls ${{ github.workspace }}
